@startuml
title Módulo 4: Emprendimiento - Casos de Uso

skinparam linetype ortho
skinparam defaultTextAlignment center
skinparam nodeSep 120
skinparam rankSep 120

left to right direction

actor "Emprendedor" as E

rectangle "Emprendimiento" {
  usecase "Crear Negocio" as UC2
  usecase "Visualizar Plantillas" as UC1
  usecase "Gestionar Sucursales" as UC4

  usecase "Personalizar Tienda" as UC3
  usecase "Vista Previa en Vivo" as UC7
  usecase "Gestionar FAQs" as UC5

  usecase "Eliminar Negocio" as UC6

  E --> UC2
  E --> UC3
  E --> UC6

  UC2 --> UC1 : <<incluye>>
  UC2 --> UC4 : <<incluye>>
  UC3 --> UC7 : <<incluye>>
  UC5 --> UC3 : <<extiende>>
}

@enduml
